#--------------------------------------------------
#  删除特定Repos的特定Secrets
#--------------------------------------------------
#

name: Delete Secrets

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 删除其他项目的Secrets
        uses: google/secrets-sync-action@v1.7.0
        with:
          SECRETS: "^[A-Z0-9_]{1}"
          REPOSITORIES: ${{ github.repository_owner }}/*
          GITHUB_TOKEN: ${{ secrets.SECRETS_SYNC_TOKEN }}
          DELETE: true
          CONCURRENCY: 10

